version: "3"
services:
  automation-execution:
    image: javadevelopmentcourse/selenium-web-automation-docker
    environment:
    - BROWSER=${BROWSER}
    - HUBHOST=hub
    - THREADCOUNT=4
    - TESTSUITE=testng-suite.xml
    volumes:
    - ./ExecutionResults/Results/vendor-portal:/home/selenium-docker/test-output
    - ./ExecutionResults/Results/flight-reservation:/home/selenium-docker/test-output