version: "3"
services:
  vendor-portal:
    image: javadevelopmentcourse/selenium-web-automation-docker
    environment:
    - BROWSER=${BROWSER}
    - HUBHOST=hub
    - THREADCOUNT=3
    - TESTSUITE=${TESTSUITE}
    volumes:
    - ./ExecutionResults/Results/vendor-portal:/home/selenium-docker/test-output
  flight-reservation-portal:
    image: javadevelopmentcourse/selenium-web-automation-docker
    environment:
    - BROWSER=${BROWSER}
    - HUBHOST=hub
    - THREADCOUNT=3
    - TESTSUITE=${TESTSUITE}
    volumes:
    - ./ExecutionResults/Results/flight-reservation:/home/selenium-docker/test-output  